### PR TITLE
Delete underscore from filename

### PR DESCRIPTION
**Pull request by ycrack**
## Overview (Required)
- Rename some vector drawable files

## Related Links
- #399

### CODE REVIEW

**Comment by takahirom** [comment]
Thanks 👍

**Comment by takahirom** [comment]
Can you merge with master? Because showing same changes in diff.

**Comment by ycrack** [comment]
Oops... 😭  What should I do? Re-send PR?

**Comment by takahirom** [comment]
Probably you can fix like this...

```
git fetch https://github.com/DroidKaigi/conference-app-2018 master:remote_master
git reset --hard remote_master
git cherry-pick 6f654e0
git push origin delete_underscore_from_filename -f
```

**Comment by takahirom** [comment]
Very clean 👍

**Comment by ycrack** [comment]
Wow! Fixed!! Thank you very much 👍

**Pull request merged**
