### PR TITLE
update gradle

### PR DESCRIPTION
**Pull request by punchdrunker**
## Issue
- close #ISSUE_NUMBER

## Overview (Required)
- update gradle version

gradle 4.5 was released! why don't we use the newest gradle?

## Links
- https://docs.gradle.org/current/release-notes.html

## Screenshot
Before | After
:--: | :--:
 |

### CODE REVIEW

**Comment by takahirom** [comment]
LGTM :+1: Thanks

**Comment by punchdrunker** [comment]
`less memory consumption` is very nice 😺

**Comment by takahirom** [comment]
Nice, I don't know that 🏆

**Comment by konifar** [comment]
LGTM!

**Pull request merged**
