### PR TITLE
fix ktlint's warnings

### PR DESCRIPTION
**Pull request by noboru-i**
## Issue
- NONE

## Overview (Required)
- fix ktlint's warnings. I found by https://424-115203383-gh.circle-artifacts.com/0/reports/ktlint/ktlint-debug.xml

## Links
- https://424-115203383-gh.circle-artifacts.com/0/reports/ktlint/ktlint-debug.xml

### CODE REVIEW

**Comment by takahirom** [comment]
Thank you for the clean code! ♻️

**Comment by noboru-i** [comment]
@takahirom 
I reduced warnings.
https://432-115203383-gh.circle-artifacts.com/0/reports/ktlint/ktlint-debug.xml

Please check. Thanks 👍

**Comment by takahirom** [comment]
Could you remove all warnings with this 😄 

```
        DataBindingUtil
                .setContentView<ActivityTopicDetailBinding>(this, R.layout.activity_topic_detail)
```

**Comment by noboru-i** [comment]
@takahirom 
https://435-115203383-gh.circle-artifacts.com/0/reports/ktlint/ktlint-debug.xml
I removed all warning 🎉

**Comment by takahirom** [comment]
🎉

**Comment by konifar** [comment]
Thanks for cleaning up our project! Baby steps 😉

**Pull request merged**
