### PR TITLE
Use java.util.Date instead of io.github.droidkaigi.confsched2018.model.Date

### LINKED ISSUE #330: [Assigned] Use java.util.Date instead of io.github.droidkaigi.confsched2018.model.Date
## Overview (Required)
- The first time we want to do kotlin-multi-platform. But Actually, In this project gave up. So we can use Java Date class
- model.Date sometimes occurs confusion

### PR DESCRIPTION
**Pull request by t-kashima**
## Issue

- close #330

## Overview (Required)

- Use java.util.Date instead of io.github.droidkaigi.confsched2018.model.Date

## Links
-

## Screenshot

It has not changed.

Before | After
:--: | :--:
 |

### CODE REVIEW

**Comment by takahirom** [comment]
👀

**Comment by konifar** [comment]
Sorry, can you merge `master` branch to fix CI ? 🙇

**Comment by takahirom** [comment]
Probably you should fix unit test imports 👍 
Probably you can do test like this
image

**Comment by t-kashima** [comment]
@takahirom  Thank you! I will try it:+1:

**Comment by takahirom** [comment]
Thank you for resolving conflict and tests 🙇 
This is if you have time.
Please use `.getTime()` instead of `.getTime().toInt()`.
Currently, `toInt()` become overflow 😭 So It is wrong.
My first motivation for this issue is this overflow.

**Comment by t-kashima** [comment]
@takahirom @konifar Thank you for your advise:pray:

**Comment by takahirom** [comment]
Looks good 👍 Thanks!!

**Pull request merged**
