### PR TITLE
Resolve waning in SessionFeedbakEntity.

### LINKED ISSUE #327: [Assigned] Resolve waning in SessionFeedbakEntity
## Overview (Required)

conference-app-2018

### PR DESCRIPTION
**Pull request by kazukinr**
## Issue
- close #327

## Overview (Required)
- Add `index=true` into SessionFeedbackEntity.sessionId.
- Increment database version.
- Migration code is not implemented because `fallbackToDestructiveMigration` is called on RoomDatabase created.

## Links
- none

## Screenshot
- none

### CODE REVIEW

**Comment by takahirom** [comment]
🆗

**Comment by takahirom** [comment]
LGTM 👍

**Comment by konifar** [comment]
LGTM! Thanks for your contribution!

**Comment by kazukinr** [comment]
Thanks for your quick review!

**Pull request merged**
