### PR TITLE
Fix broken layout in topic detail

### PR DESCRIPTION
**Pull request by kitwtnb**
## Issue
- nothing

## Overview (Required)
- Fix broken layout in topic detail

Do this view need to center text?

## Links
- nothing

## Screenshot
Before | After
:--: | :--:
|before|after|
|before2|after2|
 |

### CODE REVIEW

**Comment by konifar** [comment]
:eyes:

**Comment by konifar** [comment]
Thanks!! 
As you said, it's better to centerize ( `gravity="center"` )  the text.
Plus, I guess it needs `24dp` padding to `start` and `end`.
Can you try to fix them too? 🙇

**Comment by kitwtnb** [comment]
ok, I will fix tonight. :smile:

**Comment by konifar** [comment]
Thanks! Let me merge this at first, to prevent the other contributors fix the same issue.

**Pull request merged**
