### PR TITLE
Add doorkeeper link

### PR DESCRIPTION
**Pull request by ogapants**
## Issue
- none

## Overview (Required)
This is just an idea.
I think that you might want to add user flows for showing tiket to the app, so "Registration" was added to About app page.
And we may need to consider sentences.

## Links
- https://droidkaigi.doorkeeper.jp/events/67467

## Screenshot
Before | After
:--: | :--:
 |

### CODE REVIEW

**Comment by konifar** [comment]
:eight: 🐙 :octocat: 
Thanks for your suggestion!
It might make the users easy to show QR code in DroidKaigi.
But actually DroidKaigi have been already full so this link might the users confused.
I want to know @takahirom 's opinion.

**Comment by mhidaka** [comment]
Got it. I hope we can more maximum capacity of the conference... but I’m not sure.

**Comment by ogapants** [comment]
You are right. But I did not know how to display that QR at first...
Should I change the title from "Registration" to "doorkeeper" etc.?

**Comment by takahirom** [comment]
@mhidaka 
If we can show QR code, We can help DroidKaigi? 🤔

**Comment by takahirom** [comment]
Thank you for suggestion 👍 We rethink QR code.
This time we close this issue

**Pull request closed without merging**
