### PR TITLE
Change to use vector drawable resource instead of PNG

### PR DESCRIPTION
**Pull request by hkusu**
## Overview (Required)
For the active icon on bottom navigation, change to use vector drawable resource instead of png.

### CODE REVIEW

**Comment by konifar** [comment]
:eyes:

**Comment by hkusu** [comment]
I check svg resource on pre-lollipop device.

**Comment by konifar** [comment]
Thanks!
@takahirom Is it intentional to use png before?

**Comment by takahirom** [comment]
Probably your image is broken 🤔 
If you can fix this , Please do it 🙏 
image
image

**Comment by takahirom** [comment]
@hkusu I invited! 👍

**Comment by hkusu** [comment]
Sorry, this icon can not be successfully converted to a vector well.



I think that it is good to remain in png format.

Please close the pull request if there is no problem 🙏

**Comment by takahirom** [comment]
Thank you for challenging

**Pull request closed without merging**
