### PR TITLE
Move some files to match package location

### PR DESCRIPTION
**Pull request by itochan**
## Issue
- None

## Overview
- Fix warning of mismatch location some files.

### CODE REVIEW

**Comment by takahirom** [comment]
👀

**Comment by konifar** [comment]
I'm not familiar with the file structure for Kotlin Native, but it looks good.
It seems almost same as well as KotlinConf project.
https://github.com/JetBrains/kotlinconf-app/tree/master/common/src/main/kotlin/com/jetbrains/kotlinconf

**Comment by takahirom** [comment]
Probably I made a mistake by this file.
https://github.com/JetBrains/kotlinconf-app/tree/master/common-jvm/src/main/kotlin

**Comment by takahirom** [comment]
I am checking build just in case

**Comment by takahirom** [comment]
Thank you 👍

**Pull request merged**
