### PR TITLE
Faster Circle CI build by caching Bundle install

### LINKED ISSUE #580: [Assigned] Faster Circle CI build by caching Bundle install
## Overview (Required)
- Ruby dependencies can be cached as well as Android SDK and library dependent caching.
- If you do so, you can shorten the build time, though slightly.

## Links
- https://circleci.com/docs/2.0/language-ruby/

May I create a pull request?

### PR DESCRIPTION
**Pull request by tyutyu08**
## Issue
- close #580

## Overview (Required)
- add steps of bundle save cache and bundle restore cache

## Links
- [Using cache build](https://circleci.com/gh/DroidKaigi/conference-app-2018/1202)

### CODE REVIEW

**Comment by takahirom** [comment]
I have a question🙋 
When changing Gemfile.lock
Will ci work?

**Comment by tyutyu08** [comment]
Thanks for the question😀
When changed Gemfile.lock , Not use cache.
result:
https://circleci.com/gh/DroidKaigi/conference-app-2018/1205

I have a question.
I want to delete [21fd478](https://github.com/DroidKaigi/conference-app-2018/pull/591/commits/21fd478472ad59c912d77ad0ab0d4b7e0aaf6b45) and [b15592e](https://github.com/DroidKaigi/conference-app-2018/pull/591/commits/b15592e8a85216c1b4a8e5525ac766a989a0b4dc).
Which way should I use Force Push or Revert or Other?🤔

**Comment by takahirom** [comment]
You can use force push 👍 
git reset --hard HEAD^
git push origin add_cache_for_bundle_install

**Comment by takahirom** [comment]
Thank you for faster build 👍

**Pull request merged**
