### PR TITLE
Change launch mode of MainActivity

### PR DESCRIPTION
**Pull request by hkusu**
## Issue
- When returning to MainActivity with Back button on toolbar from MapActivity etc., MainActivity is regenerated and display state of screen is not maintained.

## Overview (Required)
- Change launch mode of MainActivity to "singleTop" to maintain the state of screen.

### CODE REVIEW

**Comment by takahirom** [comment]
Thanks 👍 
If you know, please tell me. Why does SessionDetailActivity not recreate MainActivity ?🙋

**Comment by hkusu** [comment]
In SessionDetailActirity, when back button on toolbar pressed, Activity is finish with this code.

`binding.toolbar.setNavigationOnClickListener { finish() }`

It makes no sense to specify parent Activity.

**Comment by hkusu** [comment]
fix code. Please review.

**Comment by takahirom** [comment]
Looks good 👍 
Thanks

**Pull request merged**
