### PR TITLE
Fix typo: FireStore -> Firestore

### PR DESCRIPTION
**Pull request by hironytic**
## Issue
- none

## Overview (Required)
- Fix class name and log message.
- Also fix in README. 
- I believe `Firestore` is one word.

## Links
- https://firebase.google.com/docs/firestore/

## Screenshot
- none

### CODE REVIEW

**Comment by konifar** [comment]
LGTM! 👍

**Comment by takahirom** [comment]
LGTM 👍

**Comment by konifar** [comment]
@hironytic You are mainly iOS Engineer, right?
Welcome to Android! 😄  We're glad your contribution!

**Comment by hironytic** [comment]
@konifar Yes, I'm mainly iOS engineer.
I contributed last year and it was fun. So I'm back here!! 😆

**Pull request merged**
