### PR TITLE
Resolve danger warnings and add danger-lgtm

### PR DESCRIPTION
**Pull request by gyamoto**
## Issue
- danger's warning was not resolved completly... :thinking:

## Overview (Required)
- resolve some warnings
```
- [ ] app/src/main/java/io/github/droidkaigi/confsched2018/data/api/response/mapper/SponsorDataMapperExt.kt#L7: Needless blank line(s)
- [ ] app/src/main/java/io/github/droidkaigi/confsched2018/data/db/dao/SessionFeedbackDao.kt#L13: Exceeded max line length (100)
- [ ] app/src/main/java/io/github/droidkaigi/confsched2018/di/AppModule.kt#L56: Exceeded max line length (100)
- [ ] app/src/main/java/io/github/droidkaigi/confsched2018/di/DatabaseModule.kt#L77: Unexpected blank line(s) before "}"
- [ ] app/src/main/java/io/github/droidkaigi/confsched2018/di/ViewModelFactory.kt#L8: Unused import
- [ ] app/src/main/java/io/github/droidkaigi/confsched2018/presentation/common/view/FeedbackRankingView.kt#L42: Exceeded max line length (100)
- [ ] app/src/main/java/io/github/droidkaigi/confsched2018/presentation/detail/SessionDetailFragment.kt#L102: Exceeded max line length (100)
- [ ] app/src/main/java/io/github/droidkaigi/confsched2018/presentation/sessions/feedback/SessionsFeedbackFragment.kt#L38: Line break before assignment is not allowed
- [ ] app/src/main/java/io/github/droidkaigi/confsched2018/presentation/sessions/item/SpeechSessionItem.kt#L55: Unexpected blank line(s) before "}"
- [ ] app/src/main/java/io/github/droidkaigi/confsched2018/presentation/sponsors/item/SponsorItemExt.kt#L35: Missing spacing before "->"
- [ ] app/src/main/java/io/github/droidkaigi/confsched2018/util/ext/DateExt.kt#L20: Needless blank line(s)
```

- add danger-lgtm

## Links
- https://github.com/leonhartX/danger-lgtm

## Screenshot
Before | 
:--: | :--:
After | ComingSoon

### CODE REVIEW

**Comment by takahirom** [comment]
I’d love say LGTM by myself so that Danger don't need to say so. Anyway, removing warnings are very welcome and lgtm! Because of that, can you remove danger-lgtm?

**Comment by takahirom** [comment]
@kgmyshin 🙇

**Comment by takahirom** [comment]
@gyamoto 🙇

**Comment by gyamoto** [comment]
@takahirom I understood it. Certainly, I love say LGTM by myself too! I'll remove danger-lgtm! :collision:

**Comment by takahirom** [comment]
Thanks 🙇

**Pull request merged**
