### PR TITLE
Optimize ic_launcher icon size

### LINKED ISSUE #243: [Assigned] Optimize ic_launcher icon size.
## Overview (Required)
Almost of drawables are vector-drawable.
but ic_launcher.png is png and it should be optimized.
ImageOptim might be help you. https://imageoptim.com/mac

### PR DESCRIPTION
**Pull request by kazkn**
## Issue
- close #243

## Overview (Required)
- Optimize ic_launcher.png(Look at the Screenshot)

### CODE REVIEW

**Comment by takahirom** [comment]
👀

**Comment by takahirom** [comment]
LGTM 👍 
You save our GB 😄

**Comment by konifar** [comment]
Thanks for your contribution! 👍

**Comment by kaelaela** [comment]
@kazkn Please optimize debug icons too! 😄

**Comment by kazkn** [comment]
@kaelaela It is drawable-xxhdpi icons?

**Comment by takahirom** [comment]
@kazkn I think they are these icons 👍 
https://github.com/DroidKaigi/conference-app-2018/tree/master/app/src/debug/res

**Comment by kazkn** [comment]
@takahirom Thanks! I missed that commit. Sorry.I will try optimize that.

**Comment by kazkn** [comment]
Optimized debug ic_launcher.png

**Comment by konifar** [comment]
Thanks! LGTM 👍

**Comment by kazkn** [comment]
🙇

**Pull request merged**
