### PR TITLE
disable debugs features for release

### LINKED ISSUE #71: [Assigned] Disable debug futures for Release
## Overview (Required)
- We should disable debug futures for release(Stetho, Timber)
- We can use `DebugApp` for that implementation.

### PR DESCRIPTION
**Pull request by rei-m**
## Issue
- close #71

## Overview (Required)
- Move setup of Stetho and Timber to DebugApp

## Links
- None

## Screenshot
- None

### CODE REVIEW

**Comment by takahirom** [comment]
👀

**Comment by takahirom** [comment]
Almost LGTM!! 👍 

If you have time.
I think it is better to not overriding methods.
like this

```kotlin
class DebugApp : App {
  fun onCreate() {
    super.onCreate()
    setupTimber()
    setup...
  }
  fun setupTimber() {
     Timber.plant
  }
}
class App {
   fun onCreate() {
    setupFirebase()
   }
   ...
```

What do you think?

**Comment by rei-m** [comment]
I see. I always override for debug, but I think this is better 👍

**Comment by takahirom** [comment]
Thanks!!

**Pull request merged**
