### PR TITLE
FIX TYPO

### PR DESCRIPTION
**Pull request by koogawa**
## Issue
none

## Overview (Required)
Rename a variable and file name to fix typo.

## Links
none

## Screenshot
none

### CODE REVIEW

**Comment by takahirom** [comment]
👀

**Comment by takahirom** [comment]
Thanks 👍

**Comment by konifar** [comment]
LGTM! 💯  You have eagle eyes 🦅

**Comment by konifar** [comment]
Thanks! You are mainly iOS Engineer and contributed on 2017, right?
Welcome again to Android world! 😄

**Comment by koogawa** [comment]
Yeah I came back. Thank you for your review and merge 😃

**Pull request merged**
