### PR TITLE
Add test case for the StaffViewModel

### PR DESCRIPTION
**Pull request by rkowase**
## Issue
- none

## Overview (Required)
- Add test case for the StaffViewModel

## Links
- none

## Screenshot
none

### CODE REVIEW

**Comment by rkowase** [comment]
Local unit test was passed but CircleCI failed... 😫 I'll investigate the reason why..
screen shot 2018-01-23 at 3 08 33

**Comment by konifar** [comment]
🤔  Local test by `./gradlew clean testDebug` was passed too?

**Comment by rkowase** [comment]
Yes, passed too 🤔 
```
$ ./gradlew clean testDebug
Starting a Gradle Daemon, 1 incompatible Daemon could not be reused, use --status for details

> Configure project :app 
Configuration 'compile' in project ':app' is deprecated. Use 'implementation' instead.
The CompileOptions.bootClasspath property has been deprecated and is scheduled to be removed in Gradle 5.0. Please use the CompileOptions.bootstrapClasspath property instead.
registerResGeneratingTask is deprecated, use registerGeneratedFolders(FileCollection)
registerResGeneratingTask is deprecated, use registerGeneratedFolders(FileCollection)
registerResGeneratingTask is deprecated, use registerGeneratedFolders(FileCollection)
Signing not ready. Did you specify a signingConfig for the variation Release?
registerResGeneratingTask is deprecated, use registerGeneratedFolders(FileCollection)
app: 'annotationProcessor' dependencies won't be recognized as kapt annotation processors. Please change the configuration name to 'kapt' for these artifacts: 'com.android.databinding:compiler:3.0.1'.

Build cache is an incubating feature.

> Task :app:processDebugGoogleServices 
Parsing json file: /Users/rkowase/StudioProjects/conference-app-2018/app/google-services.json

w: warning: Supported source version 'RELEASE_7' from annotation processor 'org.jetbrains.kotlin.kapt3.ProcessorWrapper' less than -source '1.8'
w: Note: Choosing cursor adapter for the return value since the query returns only 1 or 2 columns and there is a cursor adapter for the return type.
w: Note: [1] Wrote GeneratedAppGlideModule with: [com.bumptech.glide.integration.okhttp3.OkHttpLibraryGlideModule]

> Task :app:compileDebugJavaWithJavac 
Note: Some input files use unchecked or unsafe operations.
Note: Recompile with -Xlint:unchecked for details.

w: Runtime JAR files in the classpath should have the same version. These files were found in the classpath:
    /Users/rkowase/.gradle/caches/modules-2/files-2.1/org.jetbrains.kotlin/kotlin-stdlib-jre7/1.2.20/1ba23e74292b5af8980efde762fdd44fb61ddc2/kotlin-stdlib-jre7-1.2.20.jar (version 1.2)
    /Users/rkowase/.gradle/caches/modules-2/files-2.1/org.jetbrains.kotlin/kotlin-reflect/1.0.7/6f22345ea29cd01ec1da04bd28996360bcff05ae/kotlin-reflect-1.0.7.jar (version 1.0)
    /Users/rkowase/.gradle/caches/modules-2/files-2.1/org.jetbrains.kotlin/kotlin-stdlib/1.2.20/1ce9e25c74aade0aa039cce459f2906a8c8ffc8e/kotlin-stdlib-1.2.20.jar (version 1.2)
w: Consider providing an explicit dependency on kotlin-reflect 1.2 to prevent strange errors
w: Some runtime JAR files in the classpath have an incompatible version. Consider removing them from the classpath or use '-Xskip-runtime-version-check' to suppress this warning
w: Runtime JAR files in the classpath should have the same version. These files were found in the classpath:
    /Users/rkowase/.gradle/caches/modules-2/files-2.1/org.jetbrains.kotlin/kotlin-stdlib-jre7/1.2.20/1ba23e74292b5af8980efde762fdd44fb61ddc2/kotlin-stdlib-jre7-1.2.20.jar (version 1.2)
    /Users/rkowase/.gradle/caches/modules-2/files-2.1/org.jetbrains.kotlin/kotlin-reflect/1.0.7/6f22345ea29cd01ec1da04bd28996360bcff05ae/kotlin-reflect-1.0.7.jar (version 1.0)
    /Users/rkowase/.gradle/caches/modules-2/files-2.1/org.jetbrains.kotlin/kotlin-stdlib/1.2.20/1ce9e25c74aade0aa039cce459f2906a8c8ffc8e/kotlin-stdlib-1.2.20.jar (version 1.2)
w: Consider providing an explicit dependency on kotlin-reflect 1.2 to prevent strange errors
w: Some runtime JAR files in the classpath have an incompatible version. Consider removing them from the classpath or use '-Xskip-runtime-version-check' to suppress this warning
w: Runtime JAR files in the classpath should have the same version. These files were found in the classpath:
    /Users/rkowase/.gradle/caches/modules-2/files-2.1/org.jetbrains.kotlin/kotlin-stdlib-jre7/1.2.20/1ba23e74292b5af8980efde762fdd44fb61ddc2/kotlin-stdlib-jre7-1.2.20.jar (version 1.2)
    /Users/rkowase/.gradle/caches/modules-2/files-2.1/org.jetbrains.kotlin/kotlin-reflect/1.0.7/6f22345ea29cd01ec1da04bd28996360bcff05ae/kotlin-reflect-1.0.7.jar (version 1.0)
    /Users/rkowase/.gradle/caches/modules-2/files-2.1/org.jetbrains.kotlin/kotlin-stdlib/1.2.20/1ce9e25c74aade0aa039cce459f2906a8c8ffc8e/kotlin-stdlib-1.2.20.jar (version 1.2)
w: Consider providing an explicit dependency on kotlin-reflect 1.2 to prevent strange errors
w: Some runtime JAR files in the classpath have an incompatible version. Consider removing them from the classpath or use '-Xskip-runtime-version-check' to suppress this warning

BUILD SUCCESSFUL in 3m 9s
40 actionable tasks: 25 executed, 14 from cache, 1 up-to-date
```

**Comment by takahirom** [comment]
I rebuilt

**Comment by takahirom** [comment]
Is it OOM? 🤔 
https://stackoverflow.com/a/39705290/4339442

**Comment by rkowase** [comment]
passed !? it may be only a temporary failure 🤔

**Comment by takahirom** [comment]
LGTM 👍

**Pull request merged**
