### PR TITLE
fix lunch time

### PR DESCRIPTION
**Pull request by sho5nn**
## Issue
- close #ISSUE_NUMBER

## Overview (Required)

Title says everything 😉

## Links
-

## Screenshot
Before | After
:--: | :--:
device-2018-01-15-002856 | device-2018-01-15-010428

### CODE REVIEW

**Comment by takahirom** [comment]
👀

**Comment by konifar** [comment]
Oh, I didn't know that! 😮 
Thanks! LGTM 👍

**Comment by takahirom** [comment]
Thank you for keeping my lunch time! 🍖

**Comment by konifar** [comment]
Yea, thanks for @sho5nn 's fix, we can relax and eat lunch 😄

**Pull request merged**
