### PR TITLE
Use CoordinatorLayout to show SnackBar above BottomNavigationView

### PR DESCRIPTION
**Pull request by gen0083**
## Overview (Required)
- Fix Snackbar hides BottomNavigationView

## Links
- https://material.io/guidelines/components/bottom-navigation.html#bottom-navigation-specs

## Screenshot
Before | After
:--: | :--:
snackbar_over_bnv  | snackbar_above_bnv

### CODE REVIEW

**Comment by konifar** [comment]
Good catch! ⚾️

**Comment by konifar** [comment]
🙋‍♂️ 
The scroll behavior has not been changed, right?

**Comment by gen0083** [comment]
"Scroll behavior" means hide toolbar or BottomNavigationView?
If so, yes, this PR dose not change scroll behavior.

**Comment by konifar** [comment]
Got it 🆒  Then LGTM! 💯 Thanks!

**Pull request merged**
