### PR TITLE
Fix the back button behavior in the speaker detail

### LINKED ISSUE #149: [Assigned] Fix the back button behavior in the speaker detail
## Overview (Required)
When I tap the back button in the speaker detail page, the sessions list page is shown.
But I think it should be speaker search page.

20180114_115250_asus z00ad

↓

Actual | Should be
:--: | :--:
20180114_115340_asus z00ad | 20180114_115406_asus z00ad

### PR DESCRIPTION
**Pull request by kitwtnb**
## Issue
- close #149 

## Overview (Required)
- Fix the back button behavior in the speaker detail

## Links
- nothing

## Screenshot
nothing

### CODE REVIEW

**Comment by takahirom** [comment]
Thanks 👍  Can you resolve conflict?

**Comment by kitwtnb** [comment]
I fixed conflict, so please confirm. 😃

**Comment by takahirom** [comment]
LGTM 👍

**Comment by konifar** [comment]
LGTM! Thanks for contribution!

**Pull request merged**
