### PR TITLE
Stop using lineSpacing attribute before lollipop

### LINKED ISSUE #287: [Assigned] wrong margin in session feed on API Level19 emulator
## Overview (Required)
-  margin or padding for session topic label is apparently broken on api level 19

## Links
-

### LINKED ISSUE #288: [Assigned] wrong margin in session detail screen on API Level19 emulator
## Overview (Required)
similar to #287

-  margin or padding for session level label and footer textView is apparently broken on api level 19

## Links
-

### PR DESCRIPTION
**Pull request by IsseiAoki**
## Issue
- close #287, close #288

## Overview (Required)
- Fix the TextView layout problem on api level 19 or lower. TextView that using lineSpacing attribute has unnecessary spacing at bottom on api level 19 (It seems like a platform bug).
- Thanks @takahirom and @konifar for giving me good advices.

## Screenshot(Session Feed Screen / api level 19, Asus Zenfone 5)
Before | After
:--: | :--:
 | 

## Screenshot(Session Detail Screen / api level 19, Asus Zenfone 5)
Before | After
:--: | :--:
 | 

## Screenshot(Session Feed Screen / api level 23, Nexus 5X) ※Nothing changes
Before | After
:--: | :--:
 | 

## Screenshot(Session Detail Screen / api level 23, Nexus 5X) ※Nothing changes
Before | After
:--: | :--:
 |

### CODE REVIEW

**Comment by takahirom** [comment]
Thank you for taking long time 🙇
What do you think about this style? This can remove duplication

```xml
    <style name="Platform" />
    <style name="Platform.TextStyle" />
    <style name="Platform.TextStyle.App" />
    
    <style name="Platform.TextStyle.App.Title" />

    <style name="TextStyle.App.Title" parent="Platform.TextStyle.App.Title">
        <item name="android:textAppearance">@style/TextAppearance.App.Title</item>
    </style>
```

values-v21

```xml
    <style name="Platform.TextStyle.App.Title">
        <item name="android:lineSpacingMultiplier">1.25</item>
        <!-- 1.25 (Title is 21sp and "should exist as single lines", so adjusted manually) -->
    </style>
```

**Comment by IsseiAoki** [comment]
@takahirom 
Thank you for reviewing! 🙇 
I have removed duplication.

**Comment by takahirom** [comment]
I tested your style strategy like this. My device 7.1 will small red text. 🤔 

values/styles.xml

```
    <style name="TestStyle">
        <item name="android:textSize">100sp</item>
    </style>
```

values-v21/styles.xml

```
    <style name="TestStyle">
        <item name="android:textColor">#FF0000</item>
    </style>

```

**Comment by IsseiAoki** [comment]
@takahirom 
Thank you for letting me know. 👍 
Sorry! I didn't notice that the strategy does not work. I will fix it 😭

**Comment by IsseiAoki** [comment]
@takahirom 
Thank you for reviewing so many time!
I finally understood what you said. Sorry! 🙏

**Comment by takahirom** [comment]
If I do this, text becomes small red😭
I think you should move `android:textAppearance` to `TextStyle.App.Title` style.

```xml
    <style name="Platform" >
        <item name="android:textSize">100sp</item>
    </style>

    <style name="TestStyle" parent="Platform" />

```


```xml
    <style name="Platform" >
        <item name="android:textColor">#FF0000</item>
    </style>
```

**Comment by takahirom** [comment]
So sorry.
Please wait..

**Comment by IsseiAoki** [comment]
Don't mind.
I'm so sorry I'm getting confused.

**Comment by takahirom** [comment]
Your style is collect 🆗 
But, Currently, If we want to see text appearance. We should see TextStyle.App.Title and Platform.TextStyle.App.Title.
If I use this style. I can find android:textAppearance first. And If confirm want to confirm platform implementation. I can jump Platform.hogehoge.

今の実装も正しく動くと思います！
ただ、今例えばTextViewから参照していった時に2つ候補が表示され、かつ、TextApperanceとかいつでも使う要素を見るために親の要素を見にいかなくてはいけないようになっていると思います。
もし以下のようなスタイルを使えば、まず最初にどのプラットフォームでも使うandroid:textAppearance firstを見ることができ、そして、プラットフォームごとに実装を確認することができます。

values/styles.xml

```xml
    <style name="Platform" />
    <style name="Platform.TextStyle" />
    <style name="Platform.TextStyle.App" />
    
    <style name="Platform.TextStyle.App.Title" />

    <style name="TextStyle.App.Title" parent="Platform.TextStyle.App.Title">
        <item name="android:textAppearance">@style/TextAppearance.App.Title</item>
    </style>
```

values-v21/styles.xml

```xml
    <style name="Platform.TextStyle.App.Title">
        <item name="android:lineSpacingMultiplier">1.25</item>
        <!-- 1.25 (Title is 21sp and "should exist as single lines", so adjusted manually) -->
    </style>
```

**Comment by IsseiAoki** [comment]
@takahirom 
大変わかりやすいご説明どうもありがとうございます！😭 
そういった意図があったのですね。とても勉強になりました。
度々で大変申し訳ありませんが、修正をpushしましたので、ご都合の良いタイミングで再度レビューをお願い致します 🙇

**Comment by takahirom** [comment]
Thanks 👍 LGTM 
Thank you for many time refactoring! Please take rest! Good night 🌙

**Pull request merged**
