### PR TITLE
Fix AllSettionsFragment items margin 12dp

### LINKED ISSUE #358: [Assinged] Adjust sessions item margin
## Overview (Required)

[Zeplin Design](https://app.zeplin.io/project/5a327a64f0b20176887c556c/screen/5a40dfc71687acd93721052e)

Actual | Design
:--: | :--:
20180120_190017_screenshot_2018-01-20-18-59-07 jpg 1080x1920 | 20180120_190116_ _ - droidkaigi 2018 - zeplin

### PR DESCRIPTION
**Pull request by nappannda**
## Issue
- close #358 

## Overview (Required)
- Adjust sessions item margin

## Links
-

## Screenshot
Before | After
:--: | :--:
 |

### CODE REVIEW

**Comment by takahirom** [comment]
👀

**Comment by takahirom** [comment]
Looks good👍

**Comment by takahirom** [comment]
Thank you for 5 times contribution! 😄

**Comment by konifar** [comment]
Thanks!! :clap:

**Pull request merged**
