### PR TITLE
Toolbar text should be center vertical

### LINKED ISSUE #90: [Assigned] Toolbar text should be center vertical
## Overview (Required)
Toolbar text seems to be a little above the center :eyes:

20180113_162629_asus z00ad

### PR DESCRIPTION
**Pull request by beta1139**
## Issue
- close #90 

## Overview (Required)
- I Added TextView with layout_gravity is center_vertical.

## Links
- none

## Screenshot
Before | After
:--: | :--:
device-2018-01-14-045441 | device-2018-01-14-045123

 |

### CODE REVIEW

**Comment by mhidaka** [comment]
image

👀 👍

**Comment by konifar** [comment]
Thanks!
Just question :raising_hand_man: 
Can you fix this issue by using default toolbar title?
I thought this is the issue of the font spacing.

**Comment by beta1139** [comment]
I could fixed by using default toolbar title! thanks!!

**Comment by konifar** [comment]
LGTM! 👍

**Pull request merged**
