### PR TITLE
Stop to track files generated by com.google.gms:oss-licenses

### PR DESCRIPTION
**Pull request by gen0083**
## Issue
- some files updated even I don't edit any files
- `third_party_license_metadata` and `third_party_licenses` are generated by com.google.gms:oss-licenses plugin
- these files auto generated on each build
- so I think it is not necessary to track

## Overview (Required)

purge these files from Git management

### CODE REVIEW

**Comment by mhidaka** [comment]
:eyes:

**Comment by mhidaka** [comment]
Build time is shortened. great. 👍 👍 👍 

I have a question ✋ 
When adding a new third party library, do we need special process to display licenses?

**Comment by gen0083** [comment]
Although I can not say with 100% confidence, I think that it will automatically be generated by com.google.gms:oss-licenses plugin.
When we import a new library then the licenses information is added automatically by the plugin, I think... 🤔

**Comment by takahirom** [comment]
:eyes:

**Comment by takahirom** [comment]
If license screen does not work, we can revert this 👍 
And Probably DroidKaigi is OSS, so maybe you do not have to worry about that

**Comment by takahirom** [comment]
LGTM 👍

**Comment by mhidaka** [comment]
Thanks, it is a good thing.  I was satisfied.

**Pull request merged**
