### PR TITLE
Suppress color resources unused.

### LINKED ISSUE #152: [Assigned] Remove unused color resources
## Overview (Required)
Make our resources clean.

```
The resource 'R.color.day_header_text_color' appears to be unused
The resource 'R.color.card_background_color' appears to be unused
The resource 'R.color.circle_button_background' appears to be unused
```

### PR DESCRIPTION
**Pull request by jnikd**
## Issue
- close #152

## Overview (Required)
- Some color resources referenced from other resources were detected as unused.
- I suppressed them.

## Links
-

### CODE REVIEW

**Comment by konifar** [comment]
Thanks! 👍 
I thought it's okay to remove them.
What do you think? @takahirom

**Comment by takahirom** [comment]
Probably it is Android Lint bug that wrong detects.
I think it is better to suppress in lint.xml. What do you think?
https://github.com/DroidKaigi/conference-app-2018/blob/master/app/lint.xml

**Comment by konifar** [comment]
Agreed.
@jnikd Can you try to modify `lint.xml`?

**Comment by jnikd** [comment]
@konifar I'll try! thanks 😃

**Pull request closed without merging**
