### PR TITLE
fix typo of not prepared exception.

### PR DESCRIPTION
**Pull request by yagi2**
## Issue
- #73 

## Overview (Required)
- fix typo of exception name. (NotPrepairedException to NotPreparedException)

### CODE REVIEW

**Comment by takahirom** [comment]
👀

**Comment by takahirom** [comment]
Sorry I will fix ci. Wait a minute. 🙇

**Comment by konifar** [comment]
@yagi2 Sorry, our CI setting had problem. it has been already fixed.
I'll close this pr now. Can you create another PR again? 🙇

**Comment by yagi2** [comment]
@konifar 
ok! I'll close this PR and create again! please wait a minute 👍

**Pull request closed without merging**
