### PR TITLE
Update firebase version to 11.8.0 and rxjava version to 2.1.8

### LINKED ISSUE #151: [Assigned] Update firebase and rxjava version
## Overview (Required)
We should follow the latest version 😉

### PR DESCRIPTION
**Pull request by yyyske3**
## Issue
- close #151

## Overview (Required)
Update firebase version from 11.4.2 to 11.8.0 and rxjava version from 2.1.6 to 2.1.8.

I checked the release notes and there seems to be no changes that is related to codes in this app.
Besides, I did a monkey test and there seems to be no problems.

## Links
https://firebase.google.com/support/release-notes/android
https://github.com/ReactiveX/RxJava/releases/tag/v2.1.8

### CODE REVIEW

**Comment by takahirom** [comment]
Can It work with the emulator? I adjust version for the emulator. What do you think?
https://github.com/DroidKaigi/conference-app-2018/pull/160/files#diff-39e7d8c00954e920b98e7636f0ac30b2R120

**Comment by yyyske3** [comment]
Oh, I tested the app on genymotion emulator. Is it Android Studio's Emulator? I'll try it later!

**Comment by yyyske3** [comment]
Ok, same problem occoured on my emulator which has 11.7.43 version of Google Play Servcies.
With latest version Firebase(11.8.0), for example, the CompletionListener of FirebaseAuth.signInAnonymously seems not to work.

That's probably because version of Google Play Services is younger than that of Firebase.
With Firebase 11.6.2 and Google Play Services 11.7.43, there is no problems.

Then, I tried updating Android Studio's Emulator version to the latest(27.0.5).

The default Google Play Service version of this emulator version is 11.9.47.
So, the latest version of Firebase code seems to work well.

Now, I'm considering what version of Firebase should I use.
Is it ok to use just the latest version emulator?
Or is there any other problems?
Could you give me some advice?

**Comment by konifar** [comment]
@yyyske3 Thanks for checking and reporting the details!


Can you use `11.6.2`?

**Comment by yyyske3** [comment]
@konifar ok, i got it

**Comment by konifar** [comment]
Perfect! 💯  LGTM!

**Pull request merged**
