### PR TITLE
Add line wrap option to codeStyleSettings

### LINKED ISSUE #163: Add line wrap 100 characters to codeStyleSettings.xml
## Overview (Required)
- Currently, line wrap is not working.

### PR DESCRIPTION
**Pull request by rkowase**
## Issue
- close #163

## Overview (Required)
- Add line wrap option to codeStyleSettings.xml

## Links
- none

## Screenshot
none

### CODE REVIEW

**Comment by konifar** [comment]
:eyes:

**Comment by konifar** [comment]
Honestly I'm not sure this fix is enough.
Can anyone review this?

**Comment by konifar** [comment]
@rkowase It looks good. But let me wait @takahirom 's review just in case.
Please wait to merge by tomorrow 🙏  Thanks.

**Comment by takahirom** [comment]
Looks good!
This rule comes from Android Kotlin Style Guide
https://android.github.io/kotlin-guides/style.html

**Pull request merged**
