### PR TITLE
Set adaptive icon

### LINKED ISSUE #242: [Assigned] Adaptive Icon
## Overview (Required)
- DroidKaigi icon is oreo. So if we can, create Adaptive Icon

## Links
- https://developer.android.com/guide/practices/ui_guidelines/icon_design_adaptive.html

### PR DESCRIPTION
**Pull request by chigichan24**
## Issue
- close #242 

## Overview (Required)
- Add adaptive icon which consists from foreground image, background image and xml file.
- If build type is Debug, the icon will be shown grayscale image.
- Of course this animation is enabled more than API Level 25.

## Links
- https://developer.android.com/guide/practices/ui_guidelines/icon_design_adaptive.html

## Screenshot

API 26

Before | After
:--: | :--:
 | 

gif

### CODE REVIEW

**Comment by konifar** [comment]
👀

**Comment by konifar** [comment]
Cool! 🆒  Let me ask one point.
It seems too larger DroidKaigi icon than previous one for me. Is it general size?

**Comment by chigichan24** [comment]
As far as I see the mhidaka's comment and demo on issue #242, it's correct size.

**Comment by konifar** [comment]
Understood! Thanks! I learned adaptive icon for your PR!
LGTM 💯

**Pull request merged**
