### PR TITLE
Add margin in the searched topic page

### LINKED ISSUE #222: [Assigned]Add margin in the searched page.
## Overview (Required)
Sync design.

Actual | Design
:--: | :--:
20180116_213643_asus z00ad | 20180116_213820_ _ _ _rich - droidkaigi 2018 - zeplin

## Links
- https://app.zeplin.io/project/5a327a64f0b20176887c556c/screen/5a48b9e42db8817326dd696c

### PR DESCRIPTION
**Pull request by nappannda**
## Issue
- close #222

## Overview (Required)
- Add margin

## Links
-

## Screenshot
Before | After
:--: | :--:
 |

### CODE REVIEW

**Comment by takahirom** [comment]
Thank you! 👍 
Can you paste screenshot when scrolled? 👍

**Comment by nappannda** [comment]
@takahirom Please check scrolled screenshot

## Scrolled Screenshot
Before | After
:--: | :--:
 |

**Comment by takahirom** [comment]
Please wait a minute, I will talk with konifar. 🙇

**Comment by konifar** [comment]
Hi, thanks for your fix!
As @takahirom mentioned, this area should be scrolled too.

20180116_233852_34993566-14d417c0-fb14-11e7-9129-b42dc294d194 png 720x1280

I guess you can implement it by setting `paddingTop` and `clipToPadding` attributes to RecyclerView. Like this PR.
https://github.com/DroidKaigi/conference-app-2018/pull/170/files#diff-c88f525159e9f49227dae6bdd37841fdR45

Can you try to fix this? 🙇  If you have questions, feel free to ask us! Thanks

**Comment by nappannda** [comment]
@takahirom @konifar 
Fix scrolled setting

**Comment by konifar** [comment]
Perfect 👍  LGTM!

**Pull request merged**
